# Generated by Django 4.2.10 on 2025-05-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('report', 'Report'), ('appointment', 'Appointment'), ('attendance', 'Attendance'), ('treatment_plan', 'Treatment Plan'), ('equipment', 'Equipment'), ('visit', 'Visit'), ('payment', 'Payment'), ('payment_reminder', 'Payment Reminder'), ('payment_processed', 'Payment Processed'), ('payment_failed', 'Payment Failed'), ('system', 'System'), ('other', 'Other')], default='system', max_length=20),
        ),
    ]
