# Generated by Django 4.2.10 on 2025-05-03 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0003_alter_appointment_status'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('session_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('pending_reschedule', 'Pending Reschedule'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='completed', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid'), ('not_applicable', 'Not Applicable')], default='paid', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='users.therapist')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['therapist', 'date'], name='earnings_ea_therapi_1123ca_idx'), models.Index(fields=['patient', 'date'], name='earnings_ea_patient_d3c6b3_idx')],
            },
        ),
    ]
