# Generated by Django 4.2.10 on 2025-05-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_earningrecord_admin_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='earningrecord',
            name='therapist_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount for therapist', max_digits=10),
        ),
    ]
