# Generated by Django 4.2.10 on 2025-05-22 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0002_therapistreport_is_late_submission_and_more'),
        ('attendance', '0006_availability'),
        ('users', '0010_doctor_practice_area_alter_patient_address_and_more'),
        ('earnings', '0005_revenuedistributionconfig_min_admin_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this payment batch', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date when payments were/will be processed')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about this payment batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Batches',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_type', models.CharField(choices=[('monthly_15th', '15th of Every Month'), ('monthly_30th', '30th of Every Month'), ('custom', 'Custom Schedule')], default='monthly_15th', max_length=20)),
                ('custom_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month for custom schedule', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_days', models.JSONField(default=list, help_text='Days before payment to send reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['therapist__user__first_name', 'therapist__user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the session was verified by geo-tracking'),
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('upi', 'UPI'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='payment_processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference number for the payment', max_length=100),
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='payment_scheduled_date',
            field=models.DateField(blank=True, help_text='Date when payment is scheduled', null=True),
        ),
        migrations.AddField(
            model_name='earningrecord',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='earningrecord',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('partial', 'Partially Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending Payment'), ('scheduled', 'Payment Scheduled'), ('not_applicable', 'Not Applicable')], default='unpaid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='earningrecord',
            index=models.Index(fields=['payment_status'], name='earnings_ea_payment_30baa6_idx'),
        ),
        migrations.AddIndex(
            model_name='earningrecord',
            index=models.Index(fields=['payment_date'], name='earnings_ea_payment_53de8e_idx'),
        ),
        migrations.AddIndex(
            model_name='earningrecord',
            index=models.Index(fields=['payment_scheduled_date'], name='earnings_ea_payment_b4b993_idx'),
        ),
        migrations.AddIndex(
            model_name='earningrecord',
            index=models.Index(fields=['is_verified'], name='earnings_ea_is_veri_555562_idx'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='users.therapist'),
        ),
        migrations.AddField(
            model_name='paymentbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='paymentschedule',
            unique_together={('therapist', 'schedule_type')},
        ),
    ]
