# Generated by Django 4.2.10 on 2025-05-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistreport',
            name='is_late_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistreport',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='therapistreport',
            name='submission_location_accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistreport',
            name='submission_location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapistreport',
            name='submission_location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='therapistreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged'), ('late_submission', 'Late Submission')], default='draft', max_length=15),
        ),
    ]
