# Generated by Django 4.2.10 on 2025-05-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_therapistreport_is_late_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='manual_arrival_time',
            field=models.TimeField(blank=True, help_text='Manually entered arrival time', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='manual_departure_time',
            field=models.TimeField(blank=True, help_text='Manually entered departure time', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='manual_location_address',
            field=models.TextField(blank=True, help_text='Manually entered address by therapist', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='manual_location_landmark',
            field=models.CharField(blank=True, help_text='Nearest landmark to the visit location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='manual_location_notes',
            field=models.TextField(blank=True, help_text='Additional notes about the location', null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='manual_location_verified',
            field=models.BooleanField(default=False, help_text='Whether the manual location has been verified by admin'),
        ),
    ]
