# Generated by Django 5.2 on 2025-11-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(default='Ready to Begin Your Healing Journey?', max_length=200)),
                ('subheadline', models.CharField(default='Join thousands who transformed their lives with PhysioWay.', max_length=300)),
                ('primary_button_text', models.CharField(default='Book Free Consultation', max_length=50)),
                ('primary_button_link', models.CharField(default='/book-consultation', max_length=200)),
                ('show_phone_button', models.BooleanField(default=True)),
                ('background_color', models.CharField(blank=True, help_text='Leave empty for default', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='ProcessSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Simple Process', max_length=50)),
                ('title', models.CharField(default='How PhysioWay Works', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Section Settings',
                'verbose_name_plural': 'Process Section Settings',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Step number (1, 2, 3...)', unique=True)),
                ('icon', models.CharField(help_text='Emoji icon for the step', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps (How It Works)',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.TextField(help_text='Comma-separated list of features')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('link', models.CharField(default='/services', help_text='Link to service detail page', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=True, help_text='Show on landing page')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Our Expertise', max_length=50)),
                ('title', models.CharField(default='Comprehensive Services', max_length=200)),
                ('show_view_all_button', models.BooleanField(default=True)),
                ('view_all_button_text', models.CharField(default='View All Services →', max_length=50)),
                ('view_all_button_link', models.CharField(default='/services', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Section Settings',
                'verbose_name_plural': 'Services Section Settings',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='4.9/5 Rating', max_length=50)),
                ('title', models.CharField(default='What Our Patients Say', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonials Section Settings',
                'verbose_name_plural': 'Testimonials Section Settings',
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='Emoji icon', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Item',
                'verbose_name_plural': 'Why Choose Us (PhysioWay Difference)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyChooseUsSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='The PhysioWay Difference', max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Choose Us Section Settings',
                'verbose_name_plural': 'Why Choose Us Section Settings',
            },
        ),
    ]
