# Generated by Django 4.2.10 on 2025-12-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_ctasection_processsectionsettings_processstep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero image for landing page carousel (recommended: 1200x900px)', upload_to='hero/')),
                ('alt_text', models.CharField(default='Physiotherapy Treatment', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Optional caption overlay', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images (Carousel)',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='phone',
            field=models.CharField(default='+91 63532 02177', max_length=20),
        ),
    ]
