# Generated by Django 4.2.10 on 2025-12-26 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_heroimage_alter_brandingsettings_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
        migrations.AddField(
            model_name='service',
            name='conditions',
            field=models.TextField(blank=True, help_text='Comma-separated list of conditions treated'),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for service detail page', null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='long_description',
            field=models.TextField(blank=True, help_text='Detailed description for service detail page'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, help_text='URL-friendly identifier (auto-generated from title)', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
