# Generated by Django 4.2.10 on 2026-01-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_add_service_slug_and_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='image',
            field=models.ImageField(blank=True, help_text='Illustration image for the step', null=True, upload_to='process/'),
        ),
        migrations.AddField(
            model_name='whychooseus',
            name='image',
            field=models.ImageField(blank=True, help_text='Feature illustration image', null=True, upload_to='why_choose_us/'),
        ),
    ]
