# Generated by Django 4.2.10 on 2026-01-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_add_image_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('founder_type', models.CharField(choices=[('physio', 'PhysioWay Founder'), ('tech', 'Technology Partner Founder')], max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Square image recommended (400x400)', null=True, upload_to='founders/')),
                ('description', models.TextField()),
                ('qualifications', models.TextField(blank=True, help_text='Comma-separated qualifications')),
                ('company_name', models.CharField(blank=True, help_text='Company name for tech partners', max_length=100)),
                ('company_website', models.URLField(blank=True, help_text='Company website URL')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Founder',
                'verbose_name_plural': 'Founders',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('services', 'Services Page'), ('about', 'About Us Page'), ('blog', 'Blog Page'), ('contact', 'Contact Page')], max_length=20, unique=True)),
                ('hero_background_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='pages/')),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Settings',
                'verbose_name_plural': 'Page Settings',
            },
        ),
    ]
