# Generated by Django 4.2.10 on 2026-01-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_add_founder_and_page_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesettings',
            name='page',
            field=models.CharField(choices=[('services', 'Services Page'), ('about', 'About Us Page'), ('blog', 'Blog Page'), ('contact', 'Contact Page'), ('book', 'Book Consultation Page')], max_length=20, unique=True),
        ),
    ]
