# Generated by Django 4.2.10 on 2026-01-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_add_book_page_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='company_full_name',
            field=models.CharField(default='PhysioWay Active Health LLP', help_text='Full legal company name for footer and legal pages', max_length=200),
        ),
    ]
