# Generated by Django 4.2.10 on 2026-01-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_add_company_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='SEO-friendly title (60-70 characters ideal)', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Brief summary for previews and meta description (150-160 chars ideal)', max_length=300)),
                ('content', models.TextField(help_text='Full blog content in HTML format')),
                ('featured_image', models.ImageField(blank=True, help_text='Main image (1200x630 for social sharing)', null=True, upload_to='blog/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Alt text for featured image (SEO)', max_length=200)),
                ('category', models.CharField(choices=[('treatment-tips', 'Treatment Tips'), ('recovery', 'Recovery & Rehabilitation'), ('wellness', 'Health & Wellness'), ('exercises', 'Exercises & Techniques'), ('news', 'News & Updates'), ('patient-stories', 'Patient Stories')], default='treatment-tips', max_length=50)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for SEO', max_length=500)),
                ('author_name', models.CharField(default='PhysioWay Team', max_length=100)),
                ('author_title', models.CharField(blank=True, help_text='Author credentials/title', max_length=200)),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('author_bio', models.TextField(blank=True, help_text='Short author bio')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (leave blank to use title)', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (leave blank to use excerpt)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=300)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('is_published', models.BooleanField(default=False, help_text='Publish the post')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
