# Generated by Django 4.2.10 on 2025-05-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_category_equipment_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_items', to='equipment.equipment'),
        ),
    ]
