# Generated by Django 4.2.10 on 2025-05-15 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profilechangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='users.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='treatment_plans.treatmentplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailyTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('interventions', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_treatments', to='treatment_plans.treatmentplan')),
            ],
            options={
                'ordering': ['treatment_plan', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('interventions_performed', models.JSONField(default=list)),
                ('pain_level_before', models.IntegerField(blank=True, null=True)),
                ('pain_level_after', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('daily_treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='treatment_plans.dailytreatment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sessions', to='users.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_sessions', to='users.therapist')),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treatment_plans.treatmentplan')),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'indexes': [models.Index(fields=['treatment_plan', 'status'], name='treatment_p_treatme_8dc7ab_idx'), models.Index(fields=['therapist', 'status'], name='treatment_p_therapi_404125_idx'), models.Index(fields=['patient', 'status'], name='treatment_p_patient_ae1edd_idx'), models.Index(fields=['scheduled_date'], name='treatment_p_schedul_dc5539_idx')],
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_data', models.JSONField()),
                ('requested_data', models.JSONField()),
                ('reason', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_plan_changes', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_plan_changes', to=settings.AUTH_USER_MODEL)),
                ('treatment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='treatment_plans.treatmentplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['treatment_plan', 'status'], name='treatment_p_treatme_e8f6b3_idx'), models.Index(fields=['requested_by', 'status'], name='treatment_p_request_0408ee_idx'), models.Index(fields=['status'], name='treatment_p_status_86e864_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['patient', 'status'], name='treatment_p_patient_274013_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['created_by', 'status'], name='treatment_p_created_3077a4_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentplan',
            index=models.Index(fields=['status'], name='treatment_p_status_76aa28_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['category'], name='treatment_p_categor_653752_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['is_active'], name='treatment_p_is_acti_6f19fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailytreatment',
            unique_together={('treatment_plan', 'day_number')},
        ),
    ]
