# Generated by Django 4.2.10 on 2025-05-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='changed_from',
            field=models.CharField(blank=True, help_text='Previous status before change', max_length=20, null=True),
        ),
    ]
