# Generated by Django 5.2 on 2025-04-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_assessmentversion_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentversion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentversion',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='session',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentVersion',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
