# Generated by Django 4.2.10 on 2025-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendance_changed_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('approved_leave', 'Approved Leave'), ('sick_leave', 'Sick Leave'), ('emergency_leave', 'Emergency Leave'), ('available', 'Available (No Assignments)')], default='absent', max_length=20),
        ),
    ]
