# Generated by Django 4.2.10 on 2025-05-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_doctor_practice_area_alter_patient_address_and_more'),
        ('attendance', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='users.therapist')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('therapist', 'date')},
            },
        ),
    ]
