# Generated by Django 5.2 on 2025-12-01 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_availability'),
        ('scheduling', '0006_alter_appointment_treatment_plan'),
        ('users', '0011_accountdeletionrequest_dataretentionpolicy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('expected', 'Expected'), ('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('approved_leave', 'Approved Leave'), ('sick_leave', 'Sick Leave'), ('emergency_leave', 'Emergency Leave'), ('available', 'Available (No Assignments)')], default='absent', max_length=20),
        ),
        migrations.CreateModel(
            name='SessionTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('therapist_reached_time', models.DateTimeField(blank=True, help_text="Time when therapist clicked 'Reached Patient House' button", null=True)),
                ('therapist_leaving_time', models.DateTimeField(blank=True, help_text="Time when therapist clicked 'Leaving Patient House' button", null=True)),
                ('patient_confirmed_arrival', models.DateTimeField(blank=True, help_text='Time when patient confirmed therapist arrival', null=True)),
                ('patient_confirmed_departure', models.DateTimeField(blank=True, help_text='Time when patient confirmed therapist departure', null=True)),
                ('therapist_duration_minutes', models.IntegerField(blank=True, help_text='Duration calculated from therapist timestamps', null=True)),
                ('patient_confirmed_duration_minutes', models.IntegerField(blank=True, help_text='Duration calculated from patient confirmation timestamps', null=True)),
                ('has_discrepancy', models.BooleanField(default=False, help_text='True if therapist and patient times differ significantly')),
                ('discrepancy_minutes', models.IntegerField(blank=True, help_text='Difference in minutes between therapist and patient reported durations', null=True)),
                ('discrepancy_notes', models.TextField(blank=True, help_text='Admin notes about the discrepancy')),
                ('discrepancy_resolved', models.BooleanField(default=False, help_text='True if admin has reviewed and resolved the discrepancy')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('therapist_reached', 'Therapist Reached'), ('in_progress', 'In Progress'), ('therapist_left', 'Therapist Left'), ('patient_confirmed', 'Patient Confirmed'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_time_logs', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_time_logs', to='users.patient')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_session_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_time_logs', to='users.therapist')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('appointment', 'date')},
            },
        ),
    ]
