# Generated by Django 4.2.10 on 2026-01-03 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0008_add_treatment_cycle_and_reschedule_fields'),
        ('users', '0013_patient_home_latitude_and_more'),
        ('attendance', '0007_alter_attendance_status_sessiontimelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_arrival_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters when patient confirmed arrival', null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_arrival_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Patient GPS latitude when confirming therapist arrival', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_arrival_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Patient GPS longitude when confirming therapist arrival', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_departure_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters when patient confirmed departure', null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_departure_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Patient GPS latitude when confirming therapist departure', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_departure_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Patient GPS longitude when confirming therapist departure', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_arrival_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters when therapist marked arrival', null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_arrival_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Therapist GPS latitude when marking arrival', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_arrival_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Therapist GPS longitude when marking arrival', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_departure_accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters when therapist marked departure', null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_departure_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Therapist GPS latitude when marking departure', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_departure_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Therapist GPS longitude when marking departure', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='PatientConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date of the session this concern relates to')),
                ('category', models.CharField(choices=[('service_quality', 'Service Quality'), ('timing', 'Timing or Punctuality'), ('communication', 'Communication'), ('treatment', 'Treatment Approach'), ('professionalism', 'Professionalism'), ('payment', 'Payment Related'), ('other', 'Other')], default='other', max_length=20)),
                ('subject', models.CharField(help_text='Brief subject/title of the concern', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the concern')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('acknowledged', 'Acknowledged'), ('in_progress', 'Being Addressed'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's response to the patient's concern")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('requires_call', models.BooleanField(default=False, help_text='Whether admin needs to call the patient')),
                ('call_completed', models.BooleanField(default=False)),
                ('call_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Specific appointment this concern relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_concerns', to='scheduling.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='users.patient')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_concerns', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(blank=True, help_text='Therapist related to this concern (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_concerns', to='users.therapist')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'created_at'], name='attendance__patient_2832d6_idx'), models.Index(fields=['therapist', 'created_at'], name='attendance__therapi_e6c71b_idx'), models.Index(fields=['status'], name='attendance__status_5b769b_idx'), models.Index(fields=['category'], name='attendance__categor_22d7ab_idx')],
            },
        ),
    ]
