# Generated by Django 4.2.10 on 2026-01-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_sessiontimelog_patient_arrival_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_arrival_location_added_later',
            field=models.BooleanField(default=False, help_text='Whether patient arrival location was added after the initial confirmation'),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='patient_departure_location_added_later',
            field=models.BooleanField(default=False, help_text='Whether patient departure location was added after the initial confirmation'),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_arrival_location_added_later',
            field=models.BooleanField(default=False, help_text='Whether therapist arrival location was added after the initial confirmation'),
        ),
        migrations.AddField(
            model_name='sessiontimelog',
            name='therapist_departure_location_added_later',
            field=models.BooleanField(default=False, help_text='Whether therapist departure location was added after the initial confirmation'),
        ),
    ]
