# Generated by Django 5.2 on 2025-04-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='changes_log',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='mobility_issues',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='pain_level',
            field=models.CharField(blank=True, default='0', max_length=2),
        ),
        migrations.AddField(
            model_name='appointment',
            name='previous_treatments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(choices=[('initial-assessment', 'Initial Assessment'), ('follow-up', 'Follow-up Session'), ('treatment', 'Treatment Session'), ('consultation', 'Consultation'), ('emergency', 'Emergency Session')], default='initial-assessment', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
    ]
