# Generated by Django 4.2.10 on 2025-05-15 17:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='mobility_assessment',
            field=models.TextField(blank=True, help_text="Assessment of patient's mobility"),
        ),
        migrations.AddField(
            model_name='session',
            name='next_session_goals',
            field=models.TextField(blank=True, help_text='Goals for the next session'),
        ),
        migrations.AddField(
            model_name='session',
            name='pain_level_after',
            field=models.IntegerField(blank=True, help_text="Patient's pain level after treatment (0-10)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='session',
            name='pain_level_before',
            field=models.IntegerField(blank=True, help_text="Patient's pain level before treatment (0-10)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='session',
            name='patient_feedback',
            field=models.TextField(blank=True, help_text='Additional feedback from patient'),
        ),
        migrations.AddField(
            model_name='session',
            name='patient_progress',
            field=models.TextField(blank=True, help_text="Assessment of patient's progress"),
        ),
        migrations.AddField(
            model_name='session',
            name='recommendations',
            field=models.TextField(blank=True, help_text="Recommendations for patient's home care"),
        ),
        migrations.AddField(
            model_name='session',
            name='report_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='report_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='report_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='report_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('flagged', 'Flagged')], default='not_required', help_text="Status of the therapist's daily report", max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='report_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='treatment_provided',
            field=models.TextField(blank=True, help_text='Description of treatment provided during the session'),
        ),
    ]
