# Generated by Django 4.2.10 on 2025-05-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plans', '0001_initial'),
        ('scheduling', '0004_session_mobility_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='daily_treatment',
            field=models.ForeignKey(blank=True, help_text='Specific daily treatment within the plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='treatment_plans.dailytreatment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, help_text='Associated treatment plan for 15-day cycles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='treatment_plans.treatmentplan'),
        ),
    ]
