# Generated by Django 4.2.10 on 2025-10-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plans', '0001_initial'),
        ('scheduling', '0005_add_treatment_plan_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, help_text='Associated treatment plan for flexible cycle durations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='treatment_plans.treatmentplan'),
        ),
    ]
