# Generated by Django 4.2.10 on 2025-12-17 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0007_change_appointment_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_master_appointment',
            field=models.BooleanField(default=False, help_text='True if this is the master appointment that generated child appointments'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='master_appointment',
            field=models.ForeignKey(blank=True, help_text='Reference to the master appointment for child appointments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_appointments', to='scheduling.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_day_number',
            field=models.PositiveIntegerField(blank=True, help_text='Day number within the treatment cycle (1, 2, 3, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_end_date',
            field=models.DateField(blank=True, help_text='Actual end date of treatment for this appointment cycle', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_start_date',
            field=models.DateField(blank=True, help_text='Actual start date of treatment for this appointment cycle', null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='admin_note_to_therapist',
            field=models.TextField(blank=True, help_text='Note from admin to therapist about this request'),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reschedule_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, help_text='When the request was forwarded to the therapist', null=True),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='forwarded_to_therapist',
            field=models.BooleanField(default=False, help_text='Whether this request has been forwarded to the therapist'),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='patient_note',
            field=models.TextField(blank=True, help_text='Note from patient explaining the change request'),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='request_source',
            field=models.CharField(choices=[('patient', 'Patient'), ('therapist', 'Therapist'), ('admin', 'Admin')], default='therapist', help_text='Who initiated this reschedule request', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('rescheduled', 'Rescheduled'), ('pending_reschedule', 'Pending Reschedule'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reschedulerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded to Therapist')], default='pending', max_length=20),
        ),
    ]
