# Generated by Django 4.2.10 on 2025-05-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'unique_together': {('name', 'city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='TherapistServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Primary'), (2, 'Secondary'), (3, 'Tertiary')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to='areas.area')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='users.therapist')),
            ],
            options={
                'ordering': ['therapist', 'priority'],
                'unique_together': {('therapist', 'area')},
            },
        ),
        migrations.CreateModel(
            name='PatientArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='areas.area')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residential_area', to='users.patient')),
            ],
            options={
                'unique_together': {('patient', 'area')},
            },
        ),
        migrations.CreateModel(
            name='DoctorArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='areas.area')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_areas', to='users.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'area')},
            },
        ),
        migrations.CreateModel(
            name='AreaRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('therapist_patient', 'Therapist-Patient'), ('doctor_patient', 'Doctor-Patient'), ('doctor_therapist', 'Doctor-Therapist')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='areas.area')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_relationships', to='users.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_relationships', to='users.patient')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_relationships', to='users.therapist')),
            ],
            options={
                'indexes': [models.Index(fields=['area', 'relationship_type'], name='areas_arear_area_id_147c5a_idx')],
            },
        ),
    ]
