# Generated by Django 4.2.10 on 2025-05-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilechangerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='is_approved',
        ),
    ]
