# Generated by Django 4.2.10 on 2025-05-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_therapist_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='attendance_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='attendance_approved',
            field=models.BooleanField(default=False, help_text='Whether the therapist is approved to mark attendance'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='reports_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='reports_approved',
            field=models.BooleanField(default=False, help_text='Whether the therapist is approved to access and submit reports'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='treatment_plans_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='treatment_plans_approved',
            field=models.BooleanField(default=False, help_text='Whether the therapist is approved to access treatment plans'),
        ),
    ]
