# Generated by Django 4.2.10 on 2025-05-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_therapist_attendance_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
