# Generated by Django 5.2 on 2025-04-19 22:56

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctor_area_doctor_years_of_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
