# Generated by Django 4.2.10 on 2025-05-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0006_patient_emergency_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='area',
            field=models.ForeignKey(blank=True, help_text="Patient's residential area", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_patients', to='areas.area'),
        ),
    ]
