# Generated by Django 4.2.10 on 2025-05-19 21:22

from django.db import migrations


def set_default_area_for_patients(apps, schema_editor):
    """
    Set 'Ghatlodia' as the default area for all existing patients
    """
    Patient = apps.get_model('users', 'Patient')
    Area = apps.get_model('areas', 'Area')
    PatientArea = apps.get_model('areas', 'PatientArea')

    # Try to find Ghatlodia area
    ghatlodia_area = None
    try:
        # First try to find by exact name
        ghatlodia_area = Area.objects.filter(name__iexact='Ghatlodia').first()

        # If not found, try to create it
        if not ghatlodia_area:
            ghatlodia_area = Area.objects.create(
                name='Ghatlodia',
                city='Ahmedabad',
                state='Gujarat',
                zip_code='380061',
                description='Default area for existing patients'
            )
            print(f"Created default area 'Ghatlodia' with ID {ghatlodia_area.id}")
    except Exception as e:
        print(f"Error finding or creating Ghatlodia area: {str(e)}")
        return

    if not ghatlodia_area:
        print("Could not find or create Ghatlodia area. Skipping migration.")
        return

    # Update all patients without an area
    patients_without_area = Patient.objects.filter(area__isnull=True)
    updated_count = 0

    for patient in patients_without_area:
        try:
            # Set direct area reference
            patient.area = ghatlodia_area
            patient.save()

            # Also create PatientArea relationship if it doesn't exist
            PatientArea.objects.get_or_create(
                patient=patient,
                area=ghatlodia_area
            )
            updated_count += 1
        except Exception as e:
            print(f"Error updating patient {patient.id}: {str(e)}")

    print(f"Updated {updated_count} patients with default area 'Ghatlodia'")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_patient_area'),
        ('areas', '0001_initial'),  # Make sure areas app is migrated first
    ]

    operations = [
        migrations.RunPython(set_default_area_for_patients, reverse_code=migrations.RunPython.noop),
    ]
