# Generated by Django 4.2.10 on 2025-05-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0008_set_default_area_for_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='area',
            field=models.ForeignKey(help_text="Patient's residential area (required)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_patients', to='areas.area'),
        ),
    ]
