# Generated by Django 4.2.10 on 2025-05-25 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_doctor_practice_area_alter_patient_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text="User's reason for deletion request")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Review'), ('approved', 'Approved - Processing'), ('completed', 'Deletion Completed'), ('rejected', 'Rejected'), ('on_hold', 'On Hold - Legal Review')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin review notes')),
                ('deletion_type', models.CharField(blank=True, choices=[('soft', 'Soft Delete (Anonymize)'), ('hard', 'Hard Delete (Permanent)'), ('partial', 'Partial Delete (Retain Medical Records)')], max_length=20, null=True)),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('legal_hold', models.BooleanField(default=False, help_text='Legal hold prevents deletion')),
                ('legal_hold_reason', models.TextField(blank=True)),
                ('retention_override', models.BooleanField(default=False, help_text='Override deletion for retention requirements')),
                ('retention_override_reason', models.TextField(blank=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_deadline', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account Deletion Request',
                'verbose_name_plural': 'Account Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('patient_personal', 'Patient Personal Data'), ('patient_medical', 'Patient Medical Records'), ('therapist_professional', 'Therapist Professional Data'), ('doctor_professional', 'Doctor Professional Data'), ('treatment_records', 'Treatment Records'), ('appointment_history', 'Appointment History'), ('financial_records', 'Financial Records'), ('audit_logs', 'Audit Logs'), ('system_logs', 'System Logs')], max_length=50, unique=True)),
                ('retention_period_days', models.PositiveIntegerField(help_text='Number of days to retain data after deletion request')),
                ('legal_basis', models.TextField(help_text='Legal justification for retention period')),
                ('can_override_deletion', models.BooleanField(default=False, help_text='Whether this data type can override user deletion requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='data_retention_override',
            field=models.BooleanField(default=False, help_text='Override deletion for legal/medical retention requirements'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the doctor was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for account deletion request'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deletion flag for data protection compliance'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='retention_reason',
            field=models.TextField(blank=True, help_text='Legal reason for data retention override'),
        ),
        migrations.AddField(
            model_name='patient',
            name='data_retention_override',
            field=models.BooleanField(default=False, help_text='Override deletion for legal/medical retention requirements'),
        ),
        migrations.AddField(
            model_name='patient',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the patient was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='deletion_reason',
            field=models.TextField(blank=True, help_text='Reason for account deletion request'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deletion flag for data protection compliance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='retention_reason',
            field=models.TextField(blank=True, help_text='Legal reason for data retention override'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the therapist was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deletion flag'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient'), ('therapist', 'Therapist'), ('doctor', 'Doctor')], default='patient', help_text='User role is required for security and access control', max_length=10),
        ),
        migrations.CreateModel(
            name='DataAnonymizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=50)),
                ('table_name', models.CharField(max_length=100)),
                ('records_affected', models.PositiveIntegerField()),
                ('anonymization_method', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('deletion_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.accountdeletionrequest')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Anonymization Log',
                'verbose_name_plural': 'Data Anonymization Logs',
            },
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountdeletionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Compliance Report'), ('quarterly', 'Quarterly Compliance Report'), ('annual', 'Annual Compliance Report'), ('audit', 'Audit Compliance Report')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_deletion_requests', models.PositiveIntegerField(default=0)),
                ('approved_deletions', models.PositiveIntegerField(default=0)),
                ('rejected_deletions', models.PositiveIntegerField(default=0)),
                ('overdue_requests', models.PositiveIntegerField(default=0)),
                ('legal_holds', models.PositiveIntegerField(default=0)),
                ('report_data', models.JSONField(default=dict, help_text='Detailed compliance metrics')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compliance Report',
                'verbose_name_plural': 'Compliance Reports',
                'unique_together': {('report_type', 'period_start', 'period_end')},
            },
        ),
    ]
