# Generated by Django 5.2 on 2026-01-02 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_accountdeletionrequest_dataretentionpolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='added_by_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor who added this patient to the platform', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_patients', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='approved', help_text='Approval status for doctor-added patients (self-registered are auto-approved)', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the patient was approved', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor assigned to this patient for earnings distribution', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='users.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='assigned_therapist',
            field=models.ForeignKey(blank=True, help_text='Therapist assigned to this patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='users.therapist'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='denial_reason',
            field=models.TextField(blank=True, help_text='Reason for denial if applicable'),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
