# Generated by Django 4.2.10 on 2026-01-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_patient_doctor_tracking_and_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='home_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Home location latitude for safety monitoring', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the home location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='home_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Home location longitude for safety monitoring', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='current_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current/last known latitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='current_location_accuracy',
            field=models.FloatField(blank=True, help_text='Accuracy of current location in meters', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='current_location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the current location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='current_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Current/last known longitude', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location_permission_date',
            field=models.DateTimeField(blank=True, help_text='When the therapist granted location permission', null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location_permission_granted',
            field=models.BooleanField(default=False, help_text='Whether therapist has granted location permission for safety monitoring'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location_permission_revoked',
            field=models.BooleanField(default=False, help_text='Whether therapist has revoked location permission'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='location_permission_revoked_date',
            field=models.DateTimeField(blank=True, help_text='When the therapist revoked location permission', null=True),
        ),
    ]
